service: branchdna-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-dynamodb-local
  - serverless-dynamodb-seed
  - serverless-vpc-plugin
  # - serverless-offline-redis-server


custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}-branchdna
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    migration:
      dir: offline
    seed:
      domain:
        sources:
          - table: ${env:MEDIA_META_TABLE}
            sources: [./resources/seeds/movieMetaSeed.json]
          - table: ${env:USER_TABLE}
            sources: [./resources/seeds/import-users.json]
          - table: ${env:TICKETS_TABLE}
            sources: [./resources/seeds/tickets.json]
          - table: ${env:EVENTS_TABLE}
            sources: [./resources/seeds/events.json]
  seed:
    movie-meta-seed:
      table: ${env:MEDIA_META_TABLE}
      sources:
        - [./resources/seeds/movieMetaSeed.json]

  vpcConfig:
    cidrBlock: '10.0.0.0/16'
    createNatGateway: 2
    createDbSubnet: true
    zones:
      - us-east-1a
      - us-east-1b

  Route53config:
    Region: us-east-1
    Name: branchdna.pri

  ElastiCacheconfig:
    CACHE_INSTANCE_SIZE: cache.r6g.large

  SQSConfig:
    QueueName: couchtour-queue.fifo
    FifoQueue: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${env:DEPLOY_STAGE}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - sns:SetSMSAttributes
        - sns:Publish
      Resource: '*'
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
        - cognito-idp:ListUsers
      Resource: "*"

functions:
  create:
    handler: lambdas/notes/create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: lambdas/notes/get.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: lambdas/notes/list.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: lambdas/notes/update.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: lambdas/notes/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam
  purchases:
    handler: lambdas/purchases/list.main
    events:
      - http:
          path: purchases
          method: get
          cors: true
          authorizer: aws_iam

  billing:
    handler: lambdas/purchases/billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: aws_iam
  sendSMS:
    handler: lambdas/endpoints/sendSMS.handler
    events:
      - http:
          path: send-sms
          method: POST
          cors: true
          authorizer: aws_iam
  deviceActivate:
    handler: lambdas/tvapps/deviceActivate.handler
    events:
      - http:
          path: device-activate
          method: POST
          cors: true
          authorizer: aws_iam

  websocket-connect:
    handler: lambdas/websockets/connect.handler
    events:
      - websocket:
          route: $connect
          cors: true
  websocket-disconnect:
    handler: lambdas/websockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect
          cors: true
  websocket-default:
    handler: lambdas/websockets/default.handler
    events:
      - websocket:
          route: $default
          cors: true
  websocket-message:
    handler: lambdas/websockets/message.handler
    events:
      - websocket:
          route: message
          cors: true
  websocket-sendmessage:
    handler: lambdas/websockets/sendmessage.handler
    events:
      - websocket:
          route: sendmessage
          cors: true
  websocket-echo:
    handler: lambdas/websockets/echo.handler
    events:
      - websocket:
          route: echo
          cors: true
  websocket-whoami:
    handler: lambdas/websockets/whoami.handler
    events:
      - websocket:
          route: whoami
          cors: true
  websocket-onlinenow:
    handler: lambdas/websockets/onlinenow.handler
    events:
      - websocket:
          route: onlinenow
          cors: true

  ## ----------------------------------------------------------------------------------
  ## ----------------------------------------------------------------------------------
  ## -- CouchTour Admin
  websocket-upload-media-meta:
    handler: lambdas/websockets/uploadMediaMeta.handler
    events:
      - websocket:
          route: upload-media-meta
          cors: true
  ## ----------------------------------------------------------------------------------
  ## ----------------------------------------------------------------------------------
  ## -- CouchTour User Auth
  websocket-user-verify-success:
    handler: lambdas/websockets/userVerifySuccess.handler
    events:
      - websocket:
          route: user-verify-success
          cors: true
  websocket-user-verify-error:
    handler: lambdas/websockets/userVerifyError.handler
    events:
      - websocket:
          route: user-verify-error
          cors: true
  websocket-user-verify-resend-success:
    handler: lambdas/websockets/userVerifyResendSuccess.handler
    events:
      - websocket:
          route: user-verify-resend-success
          cors: true
  websocket-user-verify-resend-error:
    handler: lambdas/websockets/userVerifyResendError.handler
    events:
      - websocket:
          route: user-verify-resend-error
          cors: true
  websocket-user-login:
    handler: lambdas/websockets/userLogin.handler
    events:
      - websocket:
          route: user-login
          cors: true
  websocket-user-logout:
    handler: lambdas/websockets/userLogout.handler
    events:
      - websocket:
          route: user-logout
          cors: true
  websocket-user-signUp:
    handler: lambdas/websockets/userSignUp.handler
    events:
      - websocket:
          route: user-signup
          cors: true
  websocket-user-signUp-error:
    handler: lambdas/websockets/userSignUpError.handler
    events:
      - websocket:
          route: user-signup-error
          cors: true
  websocket-get-used-id:
    handler: lambdas/websockets/getUserId.handler
    events:
      - websocket:
          route: get-user-id
          cors: true
  ## ----------------------------------------------------------------------------------
  ## ----------------------------------------------------------------------------------
  ## -- CouchTour Patron
  websocket-get-videos:
    handler: lambdas/websockets/getVideos.handler
    events:
      - websocket:
          route: getvideos
          cors: true
  websocket-add-device-id:
    handler: lambdas/websockets/addDeviceId.handler
    events:
      - websocket:
          route: add-device-id
          cors: true
  websocket-get-user-purchases:
    handler: lambdas/websockets/getUserPurchases.handler
    events:
      - websocket:
          route: get-user-purchases
          cors: true
  ## ----------------------------------------------------------------------------------
  ## ----------------------------------------------------------------------------------
  ## -- Shows & Events
  websocket-get-user-tickets:
    handler: lambdas/websockets/getUserTickets.handler
    events:
      - websocket:
          route: get-user-tickets
          cors: true
  websocket-get-all-events:
    handler: lambdas/websockets/getAllEvents.handler
    events:
      - websocket:
          route: get-all-events
          cors: true
  websocket-get-all-tickets:
    handler: lambdas/websockets/getAllTickets.handler
    events:
      - websocket:
          route: get-all-tickets
          cors: true
  websocket-stripe-get-product-subscriptions:
    handler: lambdas/websockets/getProductSubscriptions.handler
    events:
      - websocket:
          route: get-product-subscriptions
          cors: true
  ## ----------------------------------------------------------------------------------
  ## ----------------------------------------------------------------------------------
  ## -- Strip Integration: purchase / subscriptions / products
  websocket-add-user-credit-cards:
    handler: lambdas/websockets/addUserCreditCard.handler
    events:
      - websocket:
          route: wallet-add-user-credit-card
          cors: true
  websocket-get-user-credit-cards:
    handler: lambdas/websockets/getUserCreditCards.handler
    events:
      - websocket:
          route: wallet-get-user-credit-cards
          cors: true
  websocket-delete-user-credit-cards:
    handler: lambdas/websockets/deleteUserCreditCard.handler
    events:
      - websocket:
          route: wallet-delete-user-credit-card
          cors: true
  websocket-stripe-create-purchase-request:
    handler: lambdas/websockets/createPurchaseRequest.handler
    events:
      - websocket:
          route: create-purchase-intent
          cors: true
  websocket-stripe-success-transaction-update:
    handler: lambdas/websockets/stripeProcessSuccessUpdateTransaction.handler
    events:
      - websocket:
          route: stripe-process-success-transaction-update
          cors: true
  websocket-stripe-create-user-subscriptions:
    handler: lambdas/websockets/createUserSubscriptions.handler
    events:
      - websocket:
          route: create-user-subscription
          cors: true

  # -----------------------------------------------------------------
  # --- Currently Not-Used
  #
  # websocket-update-user-credit-cards:
  #   handler: lambdas/websockets/deleteUserCreditCard.handler
  #   events:
  #     - websocket:
  #         route: wallet-update-user-credit-card
  #         cors: true
  # -----------------------------------------------------------------
  # -----------------------------------------------------------------
  # --- Stashing, Not Used
  #
  # websocket-stripe-create-payment-method:
  #   handler: lambdas/websockets/createPaymentMethod.handler
  #   events:
  #     - websocket:
  #         route: create-payment-method
  #         cors: true
  # -----------------------------------------------------------------

  ## ----------------------------------------------------------------------------------
  ## ----------------------------------------------------------------------------------
  ## -- Strip Integration: transaction :: ERROR :: handling
  websocket-stripe-error-card-deactivate:
    handler: lambdas/websockets/stripeProcessErrorCardDeactivate.handler
    events:
      - websocket:
          route: stripe-process-error-card-deactivate
          cors: true
  websocket-stripe-error-incorrect-cvc:
    handler: lambdas/websockets/stripeProcessErrorCardIncorrectCvc.handler
    events:
      - websocket:
          route: stripe-process-error-incorrect-cvc
          cors: true
  websocket-stripe-error-insufficient-funds:
    handler: lambdas/websockets/stripeProcessErrorCardInsufficientFunds.handler
    events:
      - websocket:
          route: stripe-process-error-insufficient-funds
          cors: true
  websocket-stripe-error-card-expired:
    handler: lambdas/websockets/stripeProcessErrorCardExpired.handler
    events:
      - websocket:
          route: stripe-process-error-card-expired
          cors: true
  websocket-stripe-error-payment-failure:
    handler: lambdas/websockets/stripeProcessErrorCardPaymentFailure.handler
    events:
      - websocket:
          route: stripe-process-error-payment-failure
          cors: true
  websocket-stripe-error-incorrect-zip:
    handler: lambdas/websockets/stripeProcessErrorCardIncorrectZip.handler
    events:
      - websocket:
          route: stripe-process-error-incorrect-zipcode
          cors: true

## ----------------------------------------------------------------------------------
## ----------------------------------------------------------------------------------
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
  #Route 53 Zone
  - ${file(resources/route53.yml)}
  #ElastiCache
  - ${file(resources/elasticache.yml)}
  #RDS
  - ${file(resources/rds.yml)}
  #SQS
  - ${file(resources/sqs-fifo.yml)}
  #Linux Bastion
  - ${file(resources/linux-bastion.yml)}
