Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:NOTES_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  RequestResponsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:REQUEST_RESPONSES}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: requestId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  SNSMessagesTableTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:SNS_MESSAGES_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: textId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: textId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  PurchasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:PURCHASES_TABLE}
      AttributeDefinitions:
        - AttributeName: purchaseId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: purchaseId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  MoviesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:MOVIES_TABLE}
      AttributeDefinitions:
        - AttributeName: movieId
          AttributeType: S
      KeySchema:
        - AttributeName: movieId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  SocketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:SOCKETS_TABLE}
      AttributeDefinitions:
        - AttributeName: socketId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: socketId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  # -----------------------------------------------
  # -- Media
  MediaMetaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:MEDIA_META_TABLE}
      AttributeDefinitions:
        - AttributeName: artistId
          AttributeType: S
        - AttributeName: movieId
          AttributeType: S
      KeySchema:
        - AttributeName: artistId
          KeyType: HASH
        - AttributeName: movieId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:DEVICES_TABLES}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: deviceId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  # -----------------------------------------------
  # -- Users
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:USER_TABLE}
      AttributeDefinitions:
        - AttributeName: emailAddress
          AttributeType: S
        - AttributeName: cogId
          AttributeType: S
      KeySchema:
        - AttributeName: emailAddress
          KeyType: HASH
        - AttributeName: cogId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  # -----------------------------------------------
  # -- Purchases
  CreditCardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:CREDIT_CARD_TABLE}
      AttributeDefinitions:
        - AttributeName: paymentMethodId
          AttributeType: S
        - AttributeName: emailAddress
          AttributeType: S
      KeySchema:
        - AttributeName: paymentMethodId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: emailAddressIndex
          KeySchema:
            - AttributeName: emailAddress
              KeyType: HASH
          Projection:
            ProjectionType: "ALL"
      BillingMode: PAY_PER_REQUEST
  NewPurchasesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:NEW_PURCHASES_TABLE}
      AttributeDefinitions:
        - AttributeName: creditCardId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: creditCardId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:TRANSACTIONS_TABLE}
      AttributeDefinitions:
        - AttributeName: creditCardId
          AttributeType: S
        - AttributeName: emailAddress
          AttributeType: S
      KeySchema:
        - AttributeName: creditCardId
          KeyType: HASH
        - AttributeName: emailAddress
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  UserAcquisitionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:ACQUISITIONS_TABLE}
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  StripeWebhookSuccessfulCheckout:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:STRIPE_WEBHOOK_SUCCESS_CHECKOUT}
      AttributeDefinitions:
        - AttributeName: checkoutId
          AttributeType: S
        - AttributeName: stripeCustomerId
          AttributeType: S
      KeySchema:
        - AttributeName: checkoutId
          KeyType: HASH
        - AttributeName: stripeCustomerId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  # -----------------------------------------------
  # -- Media
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:EVENTS_TABLE}
      AttributeDefinitions:
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: eventId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:TICKETS_TABLE}
      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S
        - AttributeName: eventId
          AttributeType: S
      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH
        - AttributeName: eventId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  MaestroEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:MAESTRO_EVENTS}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  MaestroSalesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${env:MAESTRO_SALES}
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  # -----------------------------------------------
  # ChatroomsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Chatrooms
  #     AttributeDefinitions:
  #       - AttributeName: chatroomId
  #         AttributeType: S
  #       - AttributeName: videoId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: chatroomId
  #         KeyType: HASH
  #       - AttributeName: videoId
  #         KeyType: RANGE
  #     BillingMode: PAY_PER_REQUEST
  # ChatMessagesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: ChatMessages
  #     AttributeDefinitions:
  #       - AttributeName: chatMessageId
  #         AttributeType: S
  #       - AttributeName: userId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: chatMessageId
  #         KeyType: HASH
  #       - AttributeName: userId
  #         KeyType: RANGE
  #     BillingMode: PAY_PER_REQUEST
  # CreditCardsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: CreditCards
  #     AttributeDefinitions:
  #       - AttributeName: creditCardId
  #         AttributeType: S
  #       - AttributeName: userId
  #         AttributeType: S
  #       - AttributeName: token
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: creditCardId
  #         KeyType: HASH
  #       - AttributeName: userId
  #         KeyType: RANGE
  #     BillingMode: PAY_PER_REQUEST
  # EventsTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Events
  #     AttributeDefinitions:
  #       - AttributeName: eventId
  #         AttributeType: S
  #       - AttributeName: createdAt
  #         AttributeType: S
  #       - AttributeName: event_date
  #         AttributeType: S
  #       - AttributeName: showtime
  #         AttributeType: S
  #       - AttributeName: title
  #         AttributeType: S
  #       - AttributeName: detail
  #         AttributeType: S
  #       - AttributeName: image
  #         AttributeType: S
  #       - AttributeName: ticket_price
  #         AttributeType: S
  #       - AttributeName: userId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: eventId
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST
  # DevicesTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: Devices
  #     AttributeDefinitions:
  #       - AttributeName: deviceId
  #         AttributeType: S
  #       - AttributeName: agent
  #         AttributeType: S
  #       - AttributeName: createdAt
  #         AttributeType: S
  #       - AttributeName: authenticatedAt
  #         AttributeType: S
  #       - AttributeName: userId
  #         AttributeType: S
  #       - AttributeName: deauthenticatedAt
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: deviceId
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST
