Resources:
  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      Engine: redis
      CacheNodeType: ${self:custom.ElastiCacheconfig.CACHE_INSTANCE_SIZE}
      NumCacheNodes: 1
      CacheSubnetGroupName:
        Ref: ElastiCacheSubnetGroup
      VpcSecurityGroupIds:
       - !Ref RedisSecurityGroup
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable Redis access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref AppSecurityGroup
  RedisRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !GetAtt 'HostedZone.Id'
      Name: !Sub 'redis.${self:custom.Route53config.Name}'
      ResourceRecords:
      - !GetAtt 'ElastiCacheCluster.RedisEndpoint.Address'
      TTL: '60'
      Type: CNAME

